### ISSUE TITLE
Need help for installation

### ISSUE THREAD

**Issue by abbar21** [mch1307/gomotics#1]
I'm stuck here... ;)
<img width="855" alt="capture d ecran 2017-11-03 a 21 05 33" src="https://user-images.githubusercontent.com/31033427/32393799-4ab5d19e-c0db-11e7-94eb-fe2865a15ac9.png">

**Comment by mch1307** [comment]
This means /opt/gomotics is not in your PATH or it does not have the exec flag. 
Try ./gomotics when launching from /opt/gomotics and make sure it has the x attributes (ls -l) If not, just do chmod +x gomotics

**Comment by abbar21** [comment]
<img width="863" alt="capture d ecran 2017-11-03 a 21 56 50" src="https://user-images.githubusercontent.com/31033427/32395585-046cda32-c0e2-11e7-82dd-b5b78f60ef2a.png">

**Comment by mch1307** [comment]
which linux are you running? 32 or 64 bits? type: uname -a
You have to download the right binary for your platform on the GitHub release page

**Comment by mch1307** [comment]
if running a linux 64, choose linux_amd64
If raspberry choose linux_arm64

**Comment by abbar21** [comment]
Linux HomeJeedom 4.9.0-4-686-pae #1 SMP Debian 4.9.51-1 (2017-09-28) i686 GNU/Linux
Do you have a 32bits release or I can do a new VM in 64bits ;)

**Comment by abbar21** [comment]
Thanks for your patience ! ;)

**Comment by mch1307** [comment]
No worries ;)
A release v.0.3.1 should appear in a few minutes with a i386 distrib, if everything goes well

**Comment by abbar21** [comment]
No lights... but : 
[gomotics.log](https://github.com/mch1307/gomotics/files/1442608/gomotics.log)
And I've this line in my script for 'Dimmer Salon"
http://192.168.1.106:8081/api/v1/jeedom/8/#slider#
Do I need to restart gomotics every time I restart Jeedom server ?

**Comment by mch1307** [comment]
in the log: listen tcp :8081: bind: address already in use
It means another process is already using port 8081 (jeedom-nhc?)
You can use another port or make sure this port is not used
PS: if you use a different port, you will need to update the Jeedom script setup accordingly

**Comment by abbar21** [comment]
Yes it is Jeedom-NHC so I took port 8082 for gomotics.
[gomotics.log](https://github.com/mch1307/gomotics/files/1442637/gomotics.log)

**Comment by abbar21** [comment]
http://192.168.1.106:8082/api/v1/jeedom/8/100 failed in a browser

**Comment by mch1307** [comment]
What's the error message? Is gomotics still running?
Can you get the list of Niko items in your browser: http://192.168.1.106:8082/api/v1/nhc?

**Comment by abbar21** [comment]
\o/ the lights working !!! "Dimmer Salon" and "Dimmer salon TV" are different now ! It may just be an impression, but it's more responsive than jeedom-NHC
What can I do to make the server automatically start at Jeedom server startup?
[gomotics.log](https://github.com/mch1307/gomotics/files/1442670/gomotics.log)

**Comment by mch1307** [comment]
Hi, 
This is good news ;)
I have written some doc on the [wiki page](https://github.com/mch1307/gomotics/wiki/Automating-gomotics-startup-on-linux-(supervisord)). Please download the latest version as I fixed a bug with the logger.
If you want to disable jeedom-nhc, edit the config file and set the startup to false instead of true.
Remember to change the log level to change the log level to info because it is verbose

**Comment by abbar21** [comment]
With supervisor, do I need confg.toml in /opt/gomotics ? If not, where can I change the listen port ?
Is it normal that stderr_logfile and stdout_logfile write in the same file ?

**Comment by mch1307** [comment]
You don't need a config file as [all parameters](https://github.com/mch1307/gomotics#env-variables) can be passed as env variables. This is what you setup in the `environment` line in supervisor config. So if you want to change the port to 8082, just add LISTEN_PORT=8082 in the supervisor config file. In your case the line would look like `environment=JEE_APIKEY="abcdefg12345",JEE_URL="http://jeedom-host/core/api/jeeApi.php",LOG_LEVEL="INFO",LOG_PATH="stdout",LISTEN_PORT="8082"`

Yes, both stderr et stdout will be written to the same log file. This is OK

**Comment by abbar21** [comment]
with http://192.168.1.106:8082/api/v1/jeedom/8/100 in a browser, I've "Item not found"... :(
[gomotics.log](https://github.com/mch1307/gomotics/files/1444314/gomotics.log)

**Comment by mch1307** [comment]
Looks like could it could not get any info from jeedom. Is jeedom up and running? Are you sure about the config? Can you post your environment line from supervisor config?

**Comment by abbar21** [comment]
It's good now. Maybe the server was not fully started. After a while I refreshed http://192.168.1.106:8082/api/v1/nhc/ and the jeedomId were good.

**Comment by abbar21** [comment]
I think I found where the problem is.
I restarted my jeedom server, and gomotics did not have jeedom info. I checked the gomotics server and the uptime was 12 minutes. After restarting the gomotics server, it was OK. Bug?

**Comment by mch1307** [comment]
Well, it's difficult to track the status of Jeedom as both processes are not linked in the startup.. So for me it's rather normal to restart gomotics after you restart jeedom..
But I will think about it ;)
