### ISSUE TITLE
How to update to 3.1.8 and help for configuration

### ISSUE THREAD

**Issue by yoyo1606** [mch1307/gomotics#10]
Hi,

I follow the wiki to configure the interface between Jeedom and NHC, i think everything is correct (look at the files below) the only warning I've got is the firmware of Jeedom is not correct, I've got the firmware 3.1.7 of Jeedom and I know in the Wiki is mentionned to have the firmware 3.1.8, but no updates are propose. I've configure Jeedom to have Beta update but still nothing.
Do you have a solution for that ?
Thanks.

![putty](https://user-images.githubusercontent.com/33864260/33075044-87957ef2-cec8-11e7-9bc4-963e109dbf84.PNG)
![winscp](https://user-images.githubusercontent.com/33864260/33075045-87b47ad2-cec8-11e7-9e7c-8d1061412b6e.PNG)
![jeedom](https://user-images.githubusercontent.com/33864260/33075449-c799ce9e-cec9-11e7-959c-2541bba0b8ad.PNG)

**Comment by mch1307** [comment]
Hi,
This is more a Jeedom question ;)
You have 2 options, either you wait for 3.1.8 to be released, or you change your jeedom installation to be in "beta", which means no official support from Jeedom.
Here is [how to switch to beta](https://github.com/jeedom/documentation/blob/master/howto/fr_FR/passer_en_beta.asciidoc)

**Comment by yoyo1606** [comment]
Thats's done I've update to 3.1.8
I've install the beta version of the plugin Script too.
All my actions up to the Jeedom interface and all room are create.
The state of each devices are good and respond when I change them over the NHC app, but when I change the state with Jeedom, this no work...
Any idea ?

![winscp v2](https://user-images.githubusercontent.com/33864260/33080329-134d05c8-ced8-11e7-8c70-db9af63afe5b.PNG)

**Comment by mch1307** [comment]
can you send the http command that has been created by gomotics in Jeedom? Based on your first screenshots, it should be http://gomotics.local:8082/api/v1/jeedom/#eqLogic_id#/xx.
Can you also provide the log? In the last screenshot, I cannot see the init parameters

**Comment by yoyo1606** [comment]
Here are the screenshots requests 

![commande http](https://user-images.githubusercontent.com/33864260/33116115-cdb21bc0-cf63-11e7-9322-b01007ea7a7c.PNG)
![winscp v3](https://user-images.githubusercontent.com/33864260/33116116-cde2bfe6-cf63-11e7-9a86-45c1e01c50a5.PNG)

**Comment by yoyo1606** [comment]
The preview log file was incomplete, here is the good one

![winscp v3](https://user-images.githubusercontent.com/33864260/33116513-582aa29e-cf65-11e7-84fb-f5bb6a869cff.PNG)

**Comment by mch1307** [comment]
gomotics.local is not resolved by your DNS, so Jeedom script is not able to properly send the command. You can use the IP address instead of gomotics.local. If gomotics runs on the same host than Jeedom, just put localhost:8082 as GM_HOSTPORT. You can get the list of equipments on http://192.168.1.200/api/v1/nhc
From this, select the JeedomID of one device and test this url: First test this url: http://192.168.1.200:8082/api/v1/jeedom/_JeedomID_/100
If this works, remove all Jeedom equipments and restart gomotics with GM_HOSTPORT set to localhost:8082 or 192.168.1.200:8082

**Comment by mch1307** [comment]
also, from your log file, it seems it is not connecting to Jeedom.
Can you upload your config file?

**Comment by yoyo1606** [comment]
I change the parameters like you said, I reload everything, on Jeedom it works twice and at the third time it no longer works... I don't understand ! 

![config toml](https://user-images.githubusercontent.com/33864260/33118603-9e0bc750-cf6c-11e7-86ed-16cd94621e7e.PNG)
![gomotics conf](https://user-images.githubusercontent.com/33864260/33118671-cbc7edd6-cf6c-11e7-9622-365e7d93d275.PNG)

**Comment by mch1307** [comment]
Is gomotics still running? You can put the log level to DEBUG, restart gomotics, reproduce and send me the log

**Comment by yoyo1606** [comment]
And now it works again... I change nothing, just I had a warning from Jeedom about JeeEvent and now nothing, it works perfectly !
Thank you very much for your time and congratulations for your work.
Do you think that you will integrate roller shutters in the future?

**Comment by mch1307** [comment]
Which version are you using? I already fixed this JeeEvent warning.
Yes I want to integrate shutters, thermostats and energy consumption, but I don't have all those modules so it is difficult

**Comment by yoyo1606** [comment]
I'am using the version 0.4.2 of gomotics, I just reload it and after, i no longer have this JeeEvent.
Good news for the futures integrations, I've a Showroom with all these modules you mentionned.
I have just a little problem, when I'm using the push button NHC (réf : XXX-52001 for example for the single push button) I'm using it for just for ON/OFF actions, when light on, the state update correctly on Jeedom but when light off, the state stay on, I've the same problem when I'm using the app NHC...

**Comment by yoyo1606** [comment]
In fact, I have to stop supervisor and then start it to see all states update automatically.
If I don't do that, states don't updates.

**Comment by mch1307** [comment]
Can you upload your supervisor config?
I guess you see all objects with Jeedom IDs when you do http://192.168.1.200:8082/api/v1/nhc from a web browser

**Comment by yoyo1606** [comment]
Below my supervisor config and the result from the web browser
![gomotics conf](https://user-images.githubusercontent.com/33864260/33134384-e01de208-cf9f-11e7-9338-d7d78facf507.PNG)
![http capture](https://user-images.githubusercontent.com/33864260/33134385-e04168c2-cf9f-11e7-8939-364afcfa2a70.PNG)

**Comment by mch1307** [comment]
Can you put the LOG_LEVEL=DEBUG, restart gomotics, swich an items from NHC and upload the log file (as text)?
You can do a replace of the API key before uploading the file

**Comment by yoyo1606** [comment]
![log gomotics](https://user-images.githubusercontent.com/33864260/33138259-5b50bcb6-cfaa-11e7-9b2a-0f67fd93488a.PNG)

**Comment by mch1307** [comment]
Please change the supervisor config and set LOG_LEVEL=DEBUG. Restart gomotics, swich an item from NHC.
Then upload the log file in plain text (no print screen)
thanks

**Comment by yoyo1606** [comment]
Here my log file in Debug mode.
I launch scene from the application Niko that light off all the lamp and another one that light on all the lights.
I also switch from an NHC switch.
[gomotics.log](https://github.com/mch1307/gomotics/files/1504969/gomotics.log)

**Comment by yoyo1606** [comment]
Some of lights state update and others no update, it's rather random...

**Comment by mch1307** [comment]
I will check your logs. There is one fix in v0.4.3 that might work for multi actions like scenario. Can you give it a try?

**Comment by yoyo1606** [comment]
Another log file when update fail
[gomotics.log](https://github.com/mch1307/gomotics/files/1505985/gomotics.log)

**Comment by mch1307** [comment]
Did you try with the latest version?

**Comment by yoyo1606** [comment]
The last log file was from the last version, that's better but there is always problem with states

**Comment by mch1307** [comment]
Can you put the LOG_LEVEL to DEBUG please, it is still in INFO.
It seems many items are updated by one action, could you check the Jeedom API logs to see if there is no error or warning?
Is this command working fine if launched from a web browser?
http://192.168.1.200/core/api/jeeApi.php?apikey=HnkDmlRjha9jqtwMFPbulHN8f9aLC0mHhqd82riZqc3ERw7B&id=2818&slider=0&type=cmd

**Comment by mch1307** [comment]
I haved pushed v0.4.4 which contains a increase of the timeout to jeedom requests. Can you give it a try?

**Comment by yoyo1606** [comment]
I install v0.4.4 of gomotics and states are more responsive.
Of course, many items are updated by one action, and when I done this action (all lights off), states update without faults but when I done the action all lights on, some states don't update.
I have another problem now with this version 0.4.4, when i launch on putty "./gomotics -conf /opt/gomotics/config.toml", everything happen good on Jeedom, all rooms and actions are create but on Putty, the command no end, even if i wait for several minutes. If I don't touch anything on putty, everything work fine but when I exit command on Putty (CTRL+C or exit), all actions on Jeedom no longer work.

![putty no end](https://user-images.githubusercontent.com/33864260/33307791-23718ff6-d418-11e7-8c74-298c674be3fa.PNG)
[gomotics (opt.gomotics).log](https://github.com/mch1307/gomotics/files/1508871/gomotics.opt.gomotics.log)
[gomotics (var.log).log](https://github.com/mch1307/gomotics/files/1508872/gomotics.var.log.log)

**Comment by mch1307** [comment]
For your "new" problem, it is normal. You launch a process running in foreground (./gomotics). If you exit your session (putty) the process will be killed.
You cannot have 2 instances of gomotics running on the same machine with different ports (one with supervisor and another one in command line). gomotics will setup http commands in jeedom that will use the host and port on which gomotics is running. If you launch it once on 8082 and another one on 8083 for example, you might end with some weird definitions in Jeedom.

**Comment by mch1307** [comment]
If you want to upgrade gomotics, stop supervisor, replace the gomotics binary with new version and restart supervisor. That's the simplest way. If you still have issues after that, can you please provide a detailed explanation. For example, when I switch on action X from NHC, only equipment Y is updated in Jeedom while I expect Y and Z to be updated. With that information and a log file, I should be able to identify the issue. Thanks

**Comment by yoyo1606** [comment]
Ok that's good now for putty.
gomotics run until yesterday and there is no bug, in fact when i encounter bugs that's when I use homebridge, I think this is this plugin that no run correctly, mostly when i launch the scene all lights on or all lights off.
When i done this when the app nhc, all states in Jeedom update correctly.
I will continue to use it in test in my show room to check fonctionnement during a long period.
I'm very interested to integer shutter, can I do this manually with the plugin script ?

**Comment by mch1307** [comment]
Good to hear that, do not hesitate to open a new issue in case you have problem.
I have created issue #11 for supporting shutters, but I don't know when I'll be able to do that ;)
