### ISSUE TITLE
One-way updState ?

### ISSUE THREAD

**Issue by abbar21** [mch1307/gomotics#2]
I think I'm a black cat ;o)
When I push on an NHC switch to turn on a lamp, the state does not change in jeedom.
The log indicates that Gomotics sends the request to jeedom but not update.
[gomotics.log](https://github.com/mch1307/gomotics/files/1444485/gomotics.log)
The return of the URL : http://192.168.1.106/core/api/jeeApi.php?apikey=abdc1234\u0026id=3\u0026slider=100\u0026type=cmd is {"jsonrpc":"2.0","id":null,"error":{"code":1,"message":"Requ\u00eate invalide. Version Jsonrpc invalide : "}}

**Comment by mch1307** [comment]
The format of the URL is correct, how did you get the return code? If it's from a web browser, it is not meaningful as you have to do a correct JSON-RPC call (not a simple htttp GET).
Anyway, the cmd ids are not correctly populated in gomotics, I will fix that soon

**Comment by abbar21** [comment]
Yes it's with a web browser.
Thank you.

**Comment by mch1307** [comment]
Can you give a try with v0.3.4?

**Comment by abbar21** [comment]
"call jeedom func only if jeedom is enabled" - OK
But no jeedom update from NHC :(
[gomotics.log](https://github.com/mch1307/gomotics/files/1447487/gomotics.log)

**Comment by mch1307** [comment]
I have just opened issue #3 for this.
Issue 2 is fixed
