### ISSUE TITLE
Wrong ID in http request to update Jeedom state

### ISSUE THREAD

**Issue by mch1307** [mch1307/gomotics#3]
The ID passed to Jeedom in the update request is the eqLogic id and not the cmd id

**Comment by mch1307** [comment]
@abbar21 the fix is in v0.3.5.
Can you please try and let me know?
Thanks

**Comment by abbar21** [comment]
Yes it works! Good work !
You should make a plugin in Jeedom and sell it as the Legrand plugin; o)
Let me know when you have a new release to test it.

**Comment by mch1307** [comment]
Happy to see it works !
Don't want to sell anything, but yes, would be nice to include this in a plugin.
I will definitely let you know when new features are available ;)
