### ISSUE TITLE
Enhancement: check if plugin script is installed at startup

### ISSUE THREAD

**Issue by mch1307** [mch1307/gomotics#5]
At startup, check if the script plugin is installed in Jeedom. 
If not, log it and disable Jeedom feature

**Comment by webalexeu** [comment]
Hello,
I've tested your upgrade, script is not detecting script plugin
"JeedomInit","level":"warning","line":42,"msg":"Script Plugin is not installed, disabling Jeedom"
Regards

**Comment by mch1307** [comment]
Hi,
Yes, have also seen that and it is fixed but not yet pushed. By the way, how did you test, it's not released yet..

**Comment by webalexeu** [comment]
Hello,
By taking the code from github
When do you plan to push it?

Thank you for your work

**Comment by mch1307** [comment]
It's easier and safer to use the pre-built binaries from the [release page](https://github.com/mch1307/gomotics/releases).
I will release as soon as I can, but I'm in a middle of a larger change (#5) and it also depends on Jeedom v3.1.8 I believe.
For now, you should use v0.3.5 from the release page
