### ISSUE TITLE
Add release for arm 386

### ISSUE THREAD

**Issue by webalexeu** [mch1307/gomotics#6]
When I switch light, update is not done.
When I check in the log, all IDs seems correct nhc ID =7, name =lampe, location=Maison, jeedom id=4, updState id=36
But URL generated is using id 4 and not id 36

Log: 
{"filename":"jeedom.go","function":"UpdateJeedomState","level":"debug","line":44,"msg":"updjeedom:  {NHC 7 switch lampe Maison 100 0 0 4 36 slider}","package":"github.com/mch1307/gomotics/server","time":"2017-11-08T23:36:40+01:00"}
{"filename":"jeedom.go","function":"UpdateJeedomState","level":"debug","line":52,"msg":"jeedom upd url:  http://localhost/core/api/jeeApi.php?apikey=xwDY5fagc1A902MI5CpCQFyi01eeMZC6\u0026id=4\u0026slider=100\u0026type=cmd","package":"github.com/mch1307/gomotics/server","time":"2017-11-08T23:36:40+01:00"}

Thank you for the support

**Comment by mch1307** [comment]
Are you sure your're using v0.3.5, looks exactly like issue #3, which was fixed in 0.3.5

**Comment by webalexeu** [comment]
Almost. I use the link you gave me yesterday.

But I need to compile from source because I'm using ARM 32bits.


Is there any way to check version used? I don't see any trace in log file


Thank you

________________________________
De : Michael Champagne <notifications@github.com>
Envoyé : jeudi 9 novembre 2017 07:06
À : mch1307/gomotics
Cc : webalexeu; Author
Objet : Re: [mch1307/gomotics] Status update not working (release 0.3.5) (#6)


Are you sure your're using v0.3.5, looks exactly like issue #3<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmch1307%2Fgomotics%2Fissues%2F3&data=02%7C01%7Calexandre.jardon%40webalex.eu%7Cb490d09a4b55443cce1a08d5273810a8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636458044096209897&sdata=uIaXnayD%2F2uf99DLQb9a3Ay419stjqaYDSM4KmcZwX4%3D&reserved=0>, which was fixed in 0.3.5

**Comment by mch1307** [comment]
I will add the platform for next releases.
In the meantime, you can do:
> git clone https://github.com/mch1307/gomotics.git

then go to the gomotics directory
> git checkout tags/v0.3.5

Then build for your platform

**Comment by webalexeu** [comment]
Hello,


Indeed, case closed. Sorry, I didn't compile correctly the correct release apparently


Following your instructions it works correctly


Thanks again


________________________________
De : Michael Champagne <notifications@github.com>
Envoyé : jeudi 9 novembre 2017 11:54
À : mch1307/gomotics
Cc : webalexeu; Author
Objet : Re: [mch1307/gomotics] Status update not working (release 0.3.5) (#6)


I will add the platform for next releases.
In the meantime, you can do:

git clone https://github.com/mch1307/gomotics.git<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmch1307%2Fgomotics.git&data=02%7C01%7Calexandre.jardon%40webalex.eu%7C5eafc7c35ea1414066d508d527605317%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636458217013049314&sdata=GiuMqN9uAQKWP7kYXqXR0Q09IN3SLQgr1E9%2FSEe5Mro%3D&reserved=0>

then go to the gomotics directory

git checkout tags/v0.3.5

Then build for your platform

**Comment by mch1307** [comment]
Good ;)
Have "transformed" the issue to an enhancement asking for arm 386 builds
Will close it when fixed
